Feature/weapon refinements
WillTarte/EMU pull request #43
Opened 2020-11-13 23:14 UTC by WillTarte

Added set of official weapons:
- Assault Riffle
- Sniper
- Shotgun
- Knife
- Grenade

Values can be tweaked ofc, but It'll be easier to balance when the game is almost complete and animations are done

2020-11-14 15:01 UTC, ClaudiaLapalme requested changes
1. I see that the knife mechanics have not been implemented yet. Is this going to be in a separate PR?

2. I see that throwables don't destroy the environment; it might be a good idea to add that since it's already in a todo

3. please no massive refactoring in a non-refactoring PR next time

2020-11-16 19:47 UTC, WillTarte commented
> 1. I see that the knife mechanics have not been implemented yet. Is this going to be in a separate PR?
> 2. I see that throwables don't destroy the environment; it might be a good idea to add that since it's already in a todo
> 3. please no massive refactoring in a non-refactoring PR next time

1. The knife melee weapon is implemented.
2. That's gonna be implemented by issue #13.
3. The point of this PR is to have a MVP weapons system.

2020-11-16 19:47 UTC, WillTarte commented on Assets/Scripts/MonoBehaviours/WeaponsSystem/ProjectileBehaviourScript.cs
> +                //todo: Deal damage to enemy
Yessir

2020-11-16 19:48 UTC, WillTarte commented on Assets/Scripts/MonoBehaviours/WeaponsSystem/ThrowableBehaviourScript.cs
> +                // todo: interacts with breakable things
That's a different issue #13

2020-11-16 19:49 UTC, WillTarte commented on Assets/Scripts/MonoBehaviours/WeaponsSystem/ProjectileBehaviourScript.cs
> +    // todo: Environment needs to be on different layers, and projectiles only interact with some of the environment layers
It's gonna be done through #13

2020-11-16 19:49 UTC, WillTarte commented on Assets/Scripts/MonoBehaviours/WeaponsSystem/ProjectileBehaviourScript.cs
> +                Destroy(gameObject);
This destroys the projectile gameobject, not the environment

2020-11-16 20:22 UTC, ClaudiaLapalme commented
The shotgun bullet speed is insanely slow. Would it be possible to just fine-tune the speed of the ammunition?

2020-11-17 20:25 UTC, ClaudiaLapalme approved these changes

2020-11-17 20:27 UTC, merged